version: '3.8'

services:
  nginx-main:
    build: 
      context: ./../nginx
    image: nginx_img-1.23.3   # en son official nginx image'ini indiriyor
    container_name: nginx-main
    ports:
      - 80:80 #http
      - 443:443 #https
    volumes:
      - ./../nginx/main:/etc/nginx/conf.d
      #buraya ne kadar aktarmak istediğimiz volume varsa aktaracağız üşenmeden
      # - ./../nginx/certs:/etc/letsencrypt/live/ostimteknik.edu.tr
      # - ./../nginx/certs:/etc/letsencrypt/live/uniclubs.co
      - ./../nginx/certs/dummy:/dummy
      # - ./nginx:/etc/nginx/conf.d/default.conf:ro  #:ro == read-only #bir süreliğine devre dışı bırakıyorum güvenlik için ileride tekrardan ayarlayacağım
    # depends_on:    # önce aşağıdaki serverların başlatılmasını bekliyor (geçersiz bir servis adı girersen hata veriyor)
    #   - sks-django-dev
    #   - sks-django-local
    #   - sks-django-prod
    #   - uc-django-dev
    #   - uc-django-local
    #   - uc-django-prod
    #   - uc-react_main-dev
    #   - uc-react_main-local
    #   - uc-react_main-prod
    #   - uc-react_pm-dev
    #   - uc-react_pm-local
    #   - uc-react_pm-prod
    restart: unless-stopped