version: '3.8'

services:
  nginx-main:
    build: 
      context: ./../nginx
    image: nginx_img-1.23.3   # en son official nginx image'ini indiriyor
    container_name: nginx-main
    ports:
      - 80:80 #http
      - 443:443 #https
    volumes:
      - ./../nginx/SKS/local:/etc/nginx/conf.d
      - ./../nginx/SKS/dev:/etc/nginx/conf.d
      - ./../nginx/certs:/etc/letsencrypt/live/ostimteknik.edu.tr
      - ./../nginx/UniClubs/local:/etc/nginx/conf.d
      - ./../nginx/UniClubs/dev:/etc/nginx/conf.d
      - ./../nginx/certs:/etc/letsencrypt/live/uniclubs.co
      # - ./nginx:/etc/nginx/conf.d/default.conf:ro  #:ro == read-only #bir süreliğine devre dışı bırakıyorum güvenlik için ileride tekrardan ayarlayacağım
    depends_on:    # önce aşağıdaki serverların başlatılmasını bekliyor 
      - sks-django-dev
      - sks-django-local
      - uc-django-dev
      - uc-django-local
      - uc-react_main-dev
      - uc-react_main-local
      - uc-react_pm-dev
      - uc-react_pm-local
    restart: unless-stopped